# Generated by Django 4.2.14 on 2025-03-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='Citie',
        ),
    ]
