# Generated by Django 4.2.14 on 2025-03-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alternate_name', models.CharField(max_length=200)),
                ('birth_year', models.DateTimeField(null=True)),
                ('death_year', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('probable_birth_date', models.DateTimeField(null=True)),
                ('probable_death_date', models.DateTimeField(null=True)),
                ('ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.ethnicity')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('religion_explanation', models.TextField(blank=True, null=True)),
                ('profession_explanation', models.TextField(blank=True, null=True)),
                ('interesting_feature', models.TextField(blank=True, null=True)),
                ('interaction_with_ordinary_explanation', models.TextField(blank=True, null=True)),
                ('interaction_with_unordinary_explanation', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('description_in_the_source', models.TextField(blank=True, null=True)),
                ('explanation_of_ethnicity', models.TextField(blank=True, null=True)),
            ],
            bases=('people.person',),
        ),
        migrations.CreateModel(
            name='UnordinaryPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
            ],
            bases=('people.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.ManyToManyField(to='people.religion'),
        ),
    ]
