# Generated by Django 4.2.14 on 2025-03-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_rename_secondarysources_secondarysource_and_more'),
        ('people', '0002_alter_person_birth_year_alter_person_death_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sources',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.writtensource'),
        ),
    ]
