# Generated by Django 4.2.14 on 2025-03-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_rename_secondarysources_secondarysource_and_more'),
        ('people', '0003_person_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sources',
        ),
        migrations.AddField(
            model_name='person',
            name='ethnicity',
            field=models.ManyToManyField(blank=True, null=True, to='people.ethnicity'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ManyToManyField(blank=True, null=True, to='people.profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='source.writtensource'),
        ),
    ]
