# Generated by Django 4.2.14 on 2025-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('year_written', models.DateField()),
                ('bibliography_information', models.TextField()),
                ('other_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_names', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_written', models.IntegerField()),
                ('known_copies', models.CharField(max_length=200)),
                ('survived_copies', models.CharField(max_length=200)),
                ('library_information', models.CharField(max_length=300)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('probable_year_written', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
