# Generated by Django 4.2.14 on 2025-03-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondarySources',
            new_name='SecondarySource',
        ),
        migrations.RenameModel(
            old_name='WrittenSources',
            new_name='WrittenSource',
        ),
    ]
